CREATE TABLE USERS (
  USER_ID        UUID NOT NULL,
  USERNAME       VARCHAR NOT NULL,
  FIRST_NAME     VARCHAR NOT NULL,
  LAST_NAME      VARCHAR NOT NULL,
  EMAIL_ADDRESS  VARCHAR NOT NULL,
  CREATION_DATE  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);