package awt.user;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.xml.bind.Marshaller;

import io.swagger.annotations.*;

/**
 * Object representation of a user.
 *
 * @author awt
 */
@ApiModel(value = "User", description = "User representation")
public class User {
    @ApiModelProperty(value = "User id. Unique value typically autogenerated by system.", readOnly = true)
    private UUID id;

    @ApiModelProperty(value = "Username")
    private String username;

    @ApiModelProperty(value = "Password. Will never be returned in payload")
    private String password;

    @ApiModelProperty(value = "First name")
    private String firstName;

    @ApiModelProperty(value = "Last name")
    private String lastName;

    @ApiModelProperty(value = "Email address")
    private String email;

    @ApiModelProperty(value = "Creation date")
    private OffsetDateTime creationDate;

    @ApiModelProperty(value = "Update date")
    private OffsetDateTime updateDate;

    public UUID getId() {
	return this.id;
    }

    public void setId(final UUID id) {
	this.id = id;
    }

    public String getUsername() {
	return this.username;
    }

    public void setUsername(final String uid) {
	this.username = uid;
    }

    public String getFirstName() {
	return this.firstName;
    }

    public void setFirstName(final String firstName) {
	this.firstName = firstName;
    }

    public String getLastName() {
	return this.lastName;
    }

    public void setLastName(final String lastName) {
	this.lastName = lastName;
    }

    public String getEmail() {
	return this.email;
    }

    public void setEmail(final String email) {
	this.email = email;
    }

    public String getPassword() {
	return this.password;
    }

    public void setPassword(final String password) {
	this.password = password;
    }

    public OffsetDateTime getCreationDate() {
	return this.creationDate;
    }

    public void setCreationDate(final OffsetDateTime creationDate) {
	this.creationDate = creationDate;
    }

    public OffsetDateTime getUpdateDate() {
	return this.updateDate;
    }

    public void setUpdateDate(final OffsetDateTime updateDate) {
	this.updateDate = updateDate;
    }

    @Override
    public String toString() {
	return "User [id=" + this.id + ", uid=" + this.username + ", firstName=" + this.firstName + ", lastName="
		+ this.lastName + ", email=" + this.email + "]";
    }

    /**
     * Primarily used to perform entity filtering.
     *
     * @param marshaller
     * @see <a href=
     *      "https://docs.oracle.com/javase/6/docs/api/javax/xml/bind/Marshaller.html#marshalEventCallback">Marshal
     *      Event Callbacks</a>
     */
    protected void beforeMarshal(final Marshaller marshaller) {
	// NOTE: the JAXB event callbacks do not work correctly within JerseyTest as
	// events are called at the wrong times. Verified this works when deployed to
	// Tomcat

	// never return password
	this.password = null; // NOPMD
    }
}